name: ooo-python
channels:
  - conda-forge
dependencies:
  # runtime dependencies
  - numpy
  - pyscf >=2.4
  - python
  - scipy
  # build dependencies
  - armadillo
  - cxx-compiler
  - cmake >=3.17
  - nanobind>=2.0
  - ninja
  - pip
  - scikit-build-core>=0.9
  # Test dependencies
  - pytest
  - pytest-cov
  - skala
